cc_test(
    name = "traj_opt_test",
    deps = [
        "//ballbot/plant/planar:ballbot_plant",
        "@googletest//:gtest_main",
    ],
    size = "large",
    srcs = ["traj_opt_test.cc"],
)

cc_test(
    name = "ballbot_plant_test",
    deps = [
        "//ballbot/plant/planar:ballbot_plant",
        "@googletest//:gtest_main",
    ],
    srcs = ["ballbot_plant_test.cc"],
)

cc_test(
  name = "linearize_test",
  deps = [
    "//ballbot/plant/planar:ballbot_plant",
    "@googletest//:gtest_main",
  ],
  srcs = ["linearize_test.cc"],
)
